### ISSUE TITLE
Setting for running cam in 4G/5G mode

### ISSUE THREAD

**Issue by motu81** [izivkov/RemoteVideoCam#11]
I'd like to use this app as a baby monitor via wireguard VPN. 
Right now it's not possible to use it without WiFi activated.

**Comment by izivkov** [comment]
Do not use this app as a baby monitor! It is not designed to be used as
such. It may freeze, sn d you will not be seeing the latest image. You need
a special certication for baby monitors and this app does not have one.
Just buy a real baby monitor.

**Comment by izivkov** [comment]
The second.part of your questions is interesting, and I will check if and
how to make it work over VPN. I'm away from home, but should be back around
the end of the month, and I'll try it.

**Comment by izivkov** [comment]
Actually, I know why it doesn't work with 4g. The 2 phones need to be on
the same router to find each other. But I'll do some more tests when I get
home.

Again, it is dandelions to use the app as a baby monitor. If the video
freezes, you may not be aware of the problem. So, should not use for this
purpose even over WiFi. I'll put a disclaimer on the web sites about this.

Regards

**Comment by izivkov** [comment]
Closed
