### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by yurtpage** [izivkov/RemoteVideoCam#17]
Please integrate the app with Weblate, Crowdwin, Transifex or Localise.com.
That would significantly simplify translations.

**Comment by izivkov** [comment]
@yurtpage 
Thanks for the suggestion. The app need almost no translation, since most screens use symbols. I rather not use a heavy, 3rd party tools for the rest.

**Comment by izivkov** [comment]
Ok, thanks. I'll take a look at the branch. Did you make a PR? If so, I'll
take a look at it, and merge if it works.

There is other work on this project, but I just don't have time to work on
it. Let me know if you are interested to contribute.

Ivo
