### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Playit3110** [izivkov/RemoteVideoCam#29]
I tried to look through some code, but java as well as kotlin are not really my type of language. I wondered how it transports the videofeed over the network. Is it some webthing like WebRTC or general streaming protocol with RTSP?

Thanks for your answer in advance.

**Comment by izivkov** [comment]
The app uses WebRTC. There is also a separate connection for signalling, which is a straight web socket. Using this connection, the two phones find each other and connect via WebRTC.

**Comment by Playit3110** [comment]
So i could also just use some web frontend to stream the video to a PC for example?

**Comment by Innomen** [comment]
I too would like more information on the output. All I want is a simple open IP camera for android. I had one ages ago but can't find it now, i thought it was just called ipcam, but humanity refuses to do this.

**Comment by izivkov** [comment]
Well, as a user, you need to install the app on 2 phones - one acts as a
camera and the other as a display. No need for a special camera. Run the
app on both phones, and they will connect automatically. Then place one of
the phones at what you want to monitor and see the live stream on the
other. That is all

**Comment by Playit3110** [comment]
> I too would like more information on the output. All I want is a simple open IP camera for android. I had one ages ago but can't find it now, i thought it was just called ipcam, but humanity refuses to do this.

Hey, you could try something like `RTSP IP-Cam Viewer` or `IPCam Demo` on FDroid

**Comment by Playit3110** [comment]
@izivkov I understand that it just works, but I would like to know, how it works.

**Comment by Innomen** [comment]
> @Innomen
> 
> > I too would like more information on the output. All I want is a simple open IP camera for android. I had one ages ago but can't find it now, i thought it was just called ipcam, but humanity refuses to do this.
> 
> Hey, you could try something like `RTSP IP-Cam Viewer` or `IPCam Demo` on FDroid

It blows my mind that there isn't a simple camera transmitter app. A client agnostic server that just outputs the video feed to an IP. I find myself very curious why. I was hoping to use this app as one if it outputs internally in some way.

**Comment by izivkov** [comment]
@Playit3110 The way this app works is the following:
1. The two phones find each other by theyr names. THere is a b uilt DNS server in every WiFi server. Eatch phone name consists of a fixed part + its IP address. This way the phones can find the other phone on the network, and can establish a connection.
2. This connection server for signalling between phe phones. They can use it to negotiate WebRTC capabilities and establish the WebRTC stream. Normally, this is dome by a WebRTC server somewhere on the web, known to both phones, but in this case they aready have a connection, so they can negotiate direct;y.

@Innomen 
[This is an RSP server](https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/RtspServerCamera1.kt) I have used in the past when I was doing some work for the OpenBot project.

**Comment by Playit3110** [comment]
Thank you very much
