### ISSUE TITLE
Crash on Android 12 OP9 Pro

### ISSUE THREAD

**Issue by redfellow** [izivkov/RemoteVideoCam#7]
Installed from App store. When I attempted to open the app, it instantly disappears.

**Comment by izivkov** [comment]
I will look at the crash report. Thanks for reporting.

**Comment by izivkov** [comment]
Please update to latest version. The crash was due to running the phone without WiFi connection. The app needs WiFi to connect to the other device.

I'm closing for now. Reopen of needed.
