### ISSUE TITLE
Implement Picture in Picture mode 

### ISSUE THREAD

**Issue by maximbaz** [izivkov/RemoteVideoCam#9]
Thanks for the awesome app! It would be extremely beneficial to be able to keep seeing and hearing the other device when the app is in background (e.g. user has opened another app). This can be achieved using Android's Picture in Picture mode, where a small window appears when user moves to home screen or to another app. I believe android takes care of the rest, e.g. allowing user to move / resize this small window, close it, etc. Let me know what you think!

**Comment by izivkov** [comment]
Good idea! I will look into it, but I will be away for the next month, and will not be able to work on this. 
If any developer wants to take a crack at this issue, just fork this repo and create a pull request. Let me know so I can assign this to you. In the mean time, I'll assign this issue to myself and work on it when I get a chance.

**Comment by izivkov** [comment]
Closing the issue for now. If anybody is interested to give it a try, please let me know and create a pull request.
